from __future__ import annotations

import importlib.util
import sys
import tarfile
import tempfile
import unittest
from pathlib import Path
from unittest import mock

ROOT = Path(__file__).resolve().parents[3]
TOOLS = ROOT / "scripts" / "release"
if str(TOOLS) not in sys.path:
    sys.path.insert(0, str(TOOLS))


def load(name: str, path: Path):
    specification = importlib.util.spec_from_file_location(name, path)
    assert specification is not None and specification.loader is not None
    module = importlib.util.module_from_spec(specification)
    sys.modules[name] = module
    specification.loader.exec_module(module)
    return module


builder = load("cigar_build_honey_demos_tests", TOOLS / "build_honey_demos.py")


class HoneyDemoProducerTests(unittest.TestCase):
    def _snapshot(self):
        # Capability/matrix authorities are generated by HNY-000. This focused
        # archive test isolates the package mapping from that separate authority test.
        authority = (
            builder.PRODUCT,
            builder.CONTRACT,
            "scripts/release/build_honey_demos.py",
        )
        with mock.patch.object(builder, "AUTHORITY_INPUTS", authority):
            return builder.snapshot(ROOT)

    def test_exact_package_contract_and_reproducible_archive(self) -> None:
        package, _payloads = self._snapshot()
        expected = {
            item["path"] if isinstance(item, dict) else item
            for item in builder.load_json(ROOT / builder.CONTRACT)["required"]
        }
        self.assertEqual(
            {entry.relative for entry in package} | {"RELEASE-METADATA.json"},
            expected,
        )
        metadata = {
            "schema_version": "cigar.release-metadata.v1",
            "artifact_id": builder.ARTIFACT_ID,
            "product_version": builder.VERSION,
            "context_abi": builder.CONTEXT_ABI,
            "source_date_epoch": 1,
            "source": {
                "revision": "1" * 40,
                "tree_sha256": "2" * 64,
                "committed": True,
                "clean": True,
            },
            "input_tree_sha256": builder._snapshot_tree_digest(package),
            "input_file_count": len(package),
            "contract": builder.CONTRACT,
            "contract_sha256": builder.sha256_file(ROOT / builder.CONTRACT),
        }
        with tempfile.TemporaryDirectory() as temporary:
            directory = Path(temporary)
            first = directory / "first.tar.gz"
            second = directory / "second.tar.gz"
            builder._write_archive(first, package, metadata, 1, False)
            builder._write_archive(second, package, metadata, 1, False)
            builder.verify_package(
                first,
                ROOT / builder.CONTRACT,
                builder.VERSION,
                builder.CONTEXT_ABI,
                1,
            )
            self.assertEqual(first.read_bytes(), second.read_bytes())
            with tarfile.open(first, "r:gz") as archive:
                names = {member.name for member in archive.getmembers()}
        self.assertEqual(names, expected)

    def test_honey_authority_exactly_selects_the_demo_artifact(self) -> None:
        authority = builder.validate_authority(ROOT)
        self.assertEqual(
            set(authority),
            {
                builder.PRODUCT,
                builder.PROFILE,
                builder.MATRIX,
                builder.REQUIREMENTS,
                builder.CONTRACT,
            },
        )

    def test_duplicate_destination_is_rejected_before_publication(self) -> None:
        duplicate = builder.PACKAGE_INPUTS[0]
        with (
            mock.patch.object(
                builder, "PACKAGE_INPUTS", (*builder.PACKAGE_INPUTS, duplicate)
            ),
            mock.patch.object(
                builder,
                "AUTHORITY_INPUTS",
                (builder.PRODUCT, builder.CONTRACT),
            ),
            self.assertRaisesRegex(
                builder.HoneyDemoBuildError, "duplicate destination"
            ),
        ):
            builder.snapshot(ROOT)


if __name__ == "__main__":
    unittest.main()
