// Code generated by sdk/generate_clients.py. DO NOT EDIT.
package cigar

import "context"

// OperationCount is the frozen v1 operation count.
const OperationCount = 45

// Operations contains the immutable v1 operation descriptors. Call Operation to receive a copy.
var operations = map[string]OperationDefinition{
	"discoverSources":          {OperationID: "discoverSources", RPC: "DiscoverSources", Service: "CatalogService", HTTPMethod: "POST", HTTPPath: "/v1/sources:discover", Mutation: false, IdempotencyRequired: false, RevisionRequired: false, Stream: false, AuthClass: "tenant", RequestType: "DiscoverSourcesRequest", ResponseType: "DiscoveryPlanResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{}},
	"ingestCatalog":            {OperationID: "ingestCatalog", RPC: "IngestCatalog", Service: "CatalogService", HTTPMethod: "POST", HTTPPath: "/v1/catalog:ingest", Mutation: true, IdempotencyRequired: true, RevisionRequired: false, Stream: false, AuthClass: "tenant", RequestType: "IngestCatalogRequest", ResponseType: "IngestionReceiptResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{}},
	"getSourceStatus":          {OperationID: "getSourceStatus", RPC: "GetSourceStatus", Service: "CatalogService", HTTPMethod: "GET", HTTPPath: "/v1/catalog/sources/{source_id}", Mutation: false, IdempotencyRequired: false, RevisionRequired: false, Stream: false, AuthClass: "tenant", RequestType: "SourceIdRequest", ResponseType: "SourceStatusResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{"source_id"}},
	"queryCatalog":             {OperationID: "queryCatalog", RPC: "QueryCatalog", Service: "CatalogService", HTTPMethod: "POST", HTTPPath: "/v1/catalog:query", Mutation: false, IdempotencyRequired: false, RevisionRequired: false, Stream: false, AuthClass: "tenant", RequestType: "QueryCatalogRequest", ResponseType: "CatalogQueryResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{}},
	"batchAtoms":               {OperationID: "batchAtoms", RPC: "BatchAtoms", Service: "CatalogService", HTTPMethod: "POST", HTTPPath: "/v1/catalog/atoms:batch", Mutation: false, IdempotencyRequired: false, RevisionRequired: false, Stream: false, AuthClass: "tenant", RequestType: "BatchAtomsRequest", ResponseType: "AtomBatchResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{}},
	"tombstoneAtom":            {OperationID: "tombstoneAtom", RPC: "TombstoneAtom", Service: "CatalogService", HTTPMethod: "POST", HTTPPath: "/v1/catalog/atoms/{atom_id}:tombstone", Mutation: true, IdempotencyRequired: true, RevisionRequired: true, Stream: false, AuthClass: "tenant", RequestType: "AtomIdRequest", ResponseType: "MutationReceipt", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{"atom_id"}},
	"createContextPlan":        {OperationID: "createContextPlan", RPC: "CreateContextPlan", Service: "ContextService", HTTPMethod: "POST", HTTPPath: "/v1/context/plans", Mutation: true, IdempotencyRequired: true, RevisionRequired: false, Stream: false, AuthClass: "tenant", RequestType: "CreateContextPlanRequest", ResponseType: "ContextPlanResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{}},
	"compileContextBundle":     {OperationID: "compileContextBundle", RPC: "CompileContextBundle", Service: "ContextService", HTTPMethod: "POST", HTTPPath: "/v1/context/bundles:compile", Mutation: true, IdempotencyRequired: true, RevisionRequired: false, Stream: false, AuthClass: "tenant", RequestType: "CompileContextBundleRequest", ResponseType: "ContextBundle", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{}},
	"compileContextDelta":      {OperationID: "compileContextDelta", RPC: "CompileContextDelta", Service: "ContextService", HTTPMethod: "POST", HTTPPath: "/v1/context/deltas:compile", Mutation: true, IdempotencyRequired: true, RevisionRequired: false, Stream: false, AuthClass: "tenant", RequestType: "CompileContextDeltaRequest", ResponseType: "ContextDeltaResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{}},
	"getContextBundle":         {OperationID: "getContextBundle", RPC: "GetContextBundle", Service: "ContextService", HTTPMethod: "GET", HTTPPath: "/v1/context/bundles/{bundle_id}", Mutation: false, IdempotencyRequired: false, RevisionRequired: false, Stream: false, AuthClass: "tenant", RequestType: "BundleIdRequest", ResponseType: "ContextBundle", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{"bundle_id"}},
	"getContextBundleManifest": {OperationID: "getContextBundleManifest", RPC: "GetContextBundleManifest", Service: "ContextService", HTTPMethod: "GET", HTTPPath: "/v1/context/bundles/{bundle_id}/manifest", Mutation: false, IdempotencyRequired: false, RevisionRequired: false, Stream: false, AuthClass: "tenant", RequestType: "BundleIdRequest", ResponseType: "SelectionManifest", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{"bundle_id"}},
	"explainContextBundle":     {OperationID: "explainContextBundle", RPC: "ExplainContextBundle", Service: "ContextService", HTTPMethod: "POST", HTTPPath: "/v1/context/bundles/{bundle_id}:explain", Mutation: true, IdempotencyRequired: true, RevisionRequired: false, Stream: false, AuthClass: "tenant", RequestType: "ExplainContextBundleRequest", ResponseType: "ContextExplanationResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{"bundle_id"}},
	"materializeContextBundle": {OperationID: "materializeContextBundle", RPC: "MaterializeContextBundle", Service: "ContextService", HTTPMethod: "POST", HTTPPath: "/v1/context/bundles/{bundle_id}:materialize", Mutation: true, IdempotencyRequired: true, RevisionRequired: false, Stream: false, AuthClass: "tenant", RequestType: "MaterializeContextBundleRequest", ResponseType: "MaterializationResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{"bundle_id"}},
	"revalidateContextBundle":  {OperationID: "revalidateContextBundle", RPC: "RevalidateContextBundle", Service: "ContextService", HTTPMethod: "POST", HTTPPath: "/v1/context/bundles/{bundle_id}:revalidate", Mutation: true, IdempotencyRequired: true, RevisionRequired: false, Stream: false, AuthClass: "tenant", RequestType: "BundleIdRequest", ResponseType: "RevalidationResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{"bundle_id"}},
	"createSpace":              {OperationID: "createSpace", RPC: "CreateSpace", Service: "SpaceService", HTTPMethod: "POST", HTTPPath: "/v1/spaces", Mutation: true, IdempotencyRequired: true, RevisionRequired: false, Stream: false, AuthClass: "tenant", RequestType: "CreateSpaceRequest", ResponseType: "ContextCommit", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{}},
	"forkSpace":                {OperationID: "forkSpace", RPC: "ForkSpace", Service: "SpaceService", HTTPMethod: "POST", HTTPPath: "/v1/spaces/{space_id}:fork", Mutation: true, IdempotencyRequired: true, RevisionRequired: true, Stream: false, AuthClass: "tenant", RequestType: "ForkSpaceRequest", ResponseType: "SpaceForkResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{"space_id"}},
	"publishSpace":             {OperationID: "publishSpace", RPC: "PublishSpace", Service: "SpaceService", HTTPMethod: "POST", HTTPPath: "/v1/spaces/{space_id}:publish", Mutation: true, IdempotencyRequired: true, RevisionRequired: true, Stream: false, AuthClass: "tenant", RequestType: "PublishSpaceRequest", ResponseType: "SpacePublishResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{"space_id"}},
	"getSpaceLog":              {OperationID: "getSpaceLog", RPC: "GetSpaceLog", Service: "SpaceService", HTTPMethod: "GET", HTTPPath: "/v1/spaces/{space_id}/log", Mutation: false, IdempotencyRequired: false, RevisionRequired: false, Stream: false, AuthClass: "tenant", RequestType: "SpaceIdRequest", ResponseType: "SpaceLogResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{"space_id"}},
	"subscribeSpaceEvents":     {OperationID: "subscribeSpaceEvents", RPC: "SubscribeSpaceEvents", Service: "SpaceService", HTTPMethod: "GET", HTTPPath: "/v1/spaces/{space_id}/events", Mutation: false, IdempotencyRequired: false, RevisionRequired: false, Stream: true, AuthClass: "tenant", RequestType: "SpaceIdRequest", ResponseType: "StreamOpenResponse", EventType: "SpaceEventPayload", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 1048576, PathFields: []string{"space_id"}},
	"createSpaceCheckpoint":    {OperationID: "createSpaceCheckpoint", RPC: "CreateSpaceCheckpoint", Service: "SpaceService", HTTPMethod: "POST", HTTPPath: "/v1/spaces/{space_id}/checkpoints", Mutation: true, IdempotencyRequired: true, RevisionRequired: true, Stream: false, AuthClass: "tenant", RequestType: "CheckpointSpaceRequest", ResponseType: "SpaceCheckpointResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{"space_id"}},
	"listSpaceConflicts":       {OperationID: "listSpaceConflicts", RPC: "ListSpaceConflicts", Service: "SpaceService", HTTPMethod: "GET", HTTPPath: "/v1/spaces/{space_id}/conflicts", Mutation: false, IdempotencyRequired: false, RevisionRequired: false, Stream: false, AuthClass: "tenant", RequestType: "SpaceIdRequest", ResponseType: "ConflictListResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{"space_id"}},
	"resolveSpaceConflict":     {OperationID: "resolveSpaceConflict", RPC: "ResolveSpaceConflict", Service: "SpaceService", HTTPMethod: "POST", HTTPPath: "/v1/spaces/{space_id}/conflicts/{conflict_id}:resolve", Mutation: true, IdempotencyRequired: true, RevisionRequired: true, Stream: false, AuthClass: "tenant", RequestType: "ResolveSpaceConflictRequest", ResponseType: "ConflictResolutionResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{"space_id", "conflict_id"}},
	"createHandoff":            {OperationID: "createHandoff", RPC: "CreateHandoff", Service: "HandoffService", HTTPMethod: "POST", HTTPPath: "/v1/handoffs", Mutation: true, IdempotencyRequired: true, RevisionRequired: false, Stream: false, AuthClass: "tenant", RequestType: "CreateHandoffRequest", ResponseType: "CreateHandoffResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{}},
	"previewHandoff":           {OperationID: "previewHandoff", RPC: "PreviewHandoff", Service: "HandoffService", HTTPMethod: "POST", HTTPPath: "/v1/handoffs/{handoff_id}:preview", Mutation: false, IdempotencyRequired: false, RevisionRequired: false, Stream: false, AuthClass: "tenant", RequestType: "HandoffIdRequest", ResponseType: "HandoffPreviewResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{"handoff_id"}},
	"acceptHandoff":            {OperationID: "acceptHandoff", RPC: "AcceptHandoff", Service: "HandoffService", HTTPMethod: "POST", HTTPPath: "/v1/handoffs/{handoff_id}:accept", Mutation: true, IdempotencyRequired: true, RevisionRequired: true, Stream: false, AuthClass: "tenant", RequestType: "AcceptHandoffRequest", ResponseType: "HandoffAcceptance", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{"handoff_id"}},
	"revokeHandoff":            {OperationID: "revokeHandoff", RPC: "RevokeHandoff", Service: "HandoffService", HTTPMethod: "POST", HTTPPath: "/v1/handoffs/{handoff_id}:revoke", Mutation: true, IdempotencyRequired: true, RevisionRequired: true, Stream: false, AuthClass: "tenant", RequestType: "RevokeHandoffRequest", ResponseType: "MutationReceipt", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{"handoff_id"}},
	"recordHandoffResult":      {OperationID: "recordHandoffResult", RPC: "RecordHandoffResult", Service: "HandoffService", HTTPMethod: "POST", HTTPPath: "/v1/handoffs/{handoff_id}/results", Mutation: true, IdempotencyRequired: true, RevisionRequired: true, Stream: false, AuthClass: "tenant", RequestType: "RecordHandoffResultRequest", ResponseType: "HandoffResultReceipt", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{"handoff_id"}},
	"mergeHandoff":             {OperationID: "mergeHandoff", RPC: "MergeHandoff", Service: "HandoffService", HTTPMethod: "POST", HTTPPath: "/v1/handoffs/{handoff_id}:merge", Mutation: true, IdempotencyRequired: true, RevisionRequired: true, Stream: false, AuthClass: "tenant", RequestType: "MergeHandoffRequest", ResponseType: "HandoffMergeResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{"handoff_id"}},
	"prepareEffect":            {OperationID: "prepareEffect", RPC: "PrepareEffect", Service: "EffectService", HTTPMethod: "POST", HTTPPath: "/v1/effects", Mutation: true, IdempotencyRequired: true, RevisionRequired: false, Stream: false, AuthClass: "tenant", RequestType: "PrepareEffectRequest", ResponseType: "EffectStatusResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{}},
	"authorizeEffect":          {OperationID: "authorizeEffect", RPC: "AuthorizeEffect", Service: "EffectService", HTTPMethod: "POST", HTTPPath: "/v1/effects/{effect_id}:authorize", Mutation: true, IdempotencyRequired: true, RevisionRequired: true, Stream: false, AuthClass: "tenant", RequestType: "AuthorizeEffectRequest", ResponseType: "EffectStatusResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{"effect_id"}},
	"dispatchEffect":           {OperationID: "dispatchEffect", RPC: "DispatchEffect", Service: "EffectService", HTTPMethod: "POST", HTTPPath: "/v1/effects/{effect_id}:dispatch", Mutation: true, IdempotencyRequired: true, RevisionRequired: true, Stream: false, AuthClass: "tenant", RequestType: "EffectIdRequest", ResponseType: "EffectStatusResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{"effect_id"}},
	"getEffectStatus":          {OperationID: "getEffectStatus", RPC: "GetEffectStatus", Service: "EffectService", HTTPMethod: "GET", HTTPPath: "/v1/effects/{effect_id}", Mutation: false, IdempotencyRequired: false, RevisionRequired: false, Stream: false, AuthClass: "tenant", RequestType: "EffectIdRequest", ResponseType: "EffectStatusResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{"effect_id"}},
	"reconcileEffect":          {OperationID: "reconcileEffect", RPC: "ReconcileEffect", Service: "EffectService", HTTPMethod: "POST", HTTPPath: "/v1/effects/{effect_id}:reconcile", Mutation: true, IdempotencyRequired: true, RevisionRequired: true, Stream: false, AuthClass: "tenant", RequestType: "EffectIdRequest", ResponseType: "EffectStatusResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{"effect_id"}},
	"compensateEffect":         {OperationID: "compensateEffect", RPC: "CompensateEffect", Service: "EffectService", HTTPMethod: "POST", HTTPPath: "/v1/effects/{effect_id}:compensate", Mutation: true, IdempotencyRequired: true, RevisionRequired: true, Stream: false, AuthClass: "tenant", RequestType: "CompensateEffectRequest", ResponseType: "EffectStatusResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{"effect_id"}},
	"createReplay":             {OperationID: "createReplay", RPC: "CreateReplay", Service: "ReplayService", HTTPMethod: "POST", HTTPPath: "/v1/replays", Mutation: true, IdempotencyRequired: true, RevisionRequired: false, Stream: false, AuthClass: "tenant", RequestType: "CreateReplayRequest", ResponseType: "ReplayJobResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{}},
	"runObservationalReplay":   {OperationID: "runObservationalReplay", RPC: "RunObservationalReplay", Service: "ReplayService", HTTPMethod: "POST", HTTPPath: "/v1/replays/{replay_id}:run", Mutation: true, IdempotencyRequired: true, RevisionRequired: false, Stream: false, AuthClass: "tenant", RequestType: "ReplayIdRequest", ResponseType: "ReplayExecution", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{"replay_id"}},
	"compareLiveReplay":        {OperationID: "compareLiveReplay", RPC: "CompareLiveReplay", Service: "ReplayService", HTTPMethod: "POST", HTTPPath: "/v1/replays/{replay_id}:compare", Mutation: true, IdempotencyRequired: true, RevisionRequired: false, Stream: false, AuthClass: "tenant", RequestType: "CompareLiveReplayRequest", ResponseType: "ReplayExecution", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{"replay_id"}},
	"getReplayCompleteness":    {OperationID: "getReplayCompleteness", RPC: "GetReplayCompleteness", Service: "ReplayService", HTTPMethod: "GET", HTTPPath: "/v1/replays/{replay_id}/completeness", Mutation: false, IdempotencyRequired: false, RevisionRequired: false, Stream: false, AuthClass: "tenant", RequestType: "ReplayIdRequest", ResponseType: "ReplayCompleteness", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{"replay_id"}},
	"getLiveness":              {OperationID: "getLiveness", RPC: "GetLiveness", Service: "OperationsService", HTTPMethod: "GET", HTTPPath: "/livez", Mutation: false, IdempotencyRequired: false, RevisionRequired: false, Stream: false, AuthClass: "health", RequestType: "EmptyRequest", ResponseType: "LivenessResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{}},
	"getReadiness":             {OperationID: "getReadiness", RPC: "GetReadiness", Service: "OperationsService", HTTPMethod: "GET", HTTPPath: "/readyz", Mutation: false, IdempotencyRequired: false, RevisionRequired: false, Stream: false, AuthClass: "health", RequestType: "EmptyRequest", ResponseType: "ReadinessResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{}},
	"getVersion":               {OperationID: "getVersion", RPC: "GetVersion", Service: "OperationsService", HTTPMethod: "GET", HTTPPath: "/v1/version", Mutation: false, IdempotencyRequired: false, RevisionRequired: false, Stream: false, AuthClass: "anonymous", RequestType: "EmptyRequest", ResponseType: "VersionResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{}},
	"getCapabilities":          {OperationID: "getCapabilities", RPC: "GetCapabilities", Service: "OperationsService", HTTPMethod: "GET", HTTPPath: "/v1/capabilities", Mutation: false, IdempotencyRequired: false, RevisionRequired: false, Stream: false, AuthClass: "anonymous", RequestType: "EmptyRequest", ResponseType: "CapabilitiesResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{}},
	"getConfiguration":         {OperationID: "getConfiguration", RPC: "GetConfiguration", Service: "OperationsService", HTTPMethod: "GET", HTTPPath: "/v1/configuration", Mutation: false, IdempotencyRequired: false, RevisionRequired: false, Stream: false, AuthClass: "operator", RequestType: "EmptyRequest", ResponseType: "ConfigurationResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{}},
	"getDiagnostics":           {OperationID: "getDiagnostics", RPC: "GetDiagnostics", Service: "OperationsService", HTTPMethod: "GET", HTTPPath: "/v1/diagnostics", Mutation: false, IdempotencyRequired: false, RevisionRequired: false, Stream: false, AuthClass: "operator", RequestType: "EmptyRequest", ResponseType: "DiagnosticsResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{}},
	"getMetrics":               {OperationID: "getMetrics", RPC: "GetMetrics", Service: "OperationsService", HTTPMethod: "GET", HTTPPath: "/metrics", Mutation: false, IdempotencyRequired: false, RevisionRequired: false, Stream: false, AuthClass: "operator", RequestType: "EmptyRequest", ResponseType: "MetricsResponse", EventType: "", RequestMaxBytes: 16777216, ResponseMaxBytes: 16777216, EventMaxBytes: 0, PathFields: []string{}},
}

var payloadTypes = []string{
	"AcceptHandoffRequest",
	"AtomBatchResponse",
	"AtomIdRequest",
	"AuthorizeEffectRequest",
	"BatchAtomsRequest",
	"BundleIdRequest",
	"CapabilitiesResponse",
	"CatalogQueryResponse",
	"CheckpointSpaceRequest",
	"CompareLiveReplayRequest",
	"CompensateEffectRequest",
	"CompileContextBundleRequest",
	"CompileContextDeltaRequest",
	"ConfigurationResponse",
	"ConflictListResponse",
	"ConflictResolutionResponse",
	"ContextBundle",
	"ContextCommit",
	"ContextDeltaResponse",
	"ContextExplanationResponse",
	"ContextPlanResponse",
	"CreateContextPlanRequest",
	"CreateHandoffRequest",
	"CreateHandoffResponse",
	"CreateReplayRequest",
	"CreateSpaceRequest",
	"DiagnosticsResponse",
	"DiscoverSourcesRequest",
	"DiscoveryPlanResponse",
	"EffectIdRequest",
	"EffectStatusResponse",
	"EmptyRequest",
	"ExplainContextBundleRequest",
	"ForkSpaceRequest",
	"HandoffAcceptance",
	"HandoffIdRequest",
	"HandoffMergeResponse",
	"HandoffPreviewResponse",
	"HandoffResultReceipt",
	"IngestCatalogRequest",
	"IngestionReceiptResponse",
	"LivenessResponse",
	"MaterializationResponse",
	"MaterializeContextBundleRequest",
	"MergeHandoffRequest",
	"MetricsResponse",
	"MutationReceipt",
	"PrepareEffectRequest",
	"PublishSpaceRequest",
	"QueryCatalogRequest",
	"ReadinessResponse",
	"RecordHandoffResultRequest",
	"ReplayCompleteness",
	"ReplayExecution",
	"ReplayIdRequest",
	"ReplayJobResponse",
	"ResolveSpaceConflictRequest",
	"RevalidationResponse",
	"RevokeHandoffRequest",
	"SelectionManifest",
	"SourceIdRequest",
	"SourceStatusResponse",
	"SpaceCheckpointResponse",
	"SpaceEventPayload",
	"SpaceForkResponse",
	"SpaceIdRequest",
	"SpaceLogResponse",
	"SpacePublishResponse",
	"StreamOpenResponse",
	"VersionResponse",
}

// PayloadTypeNames returns a copy of operation-specific payload names in canonical order.
func PayloadTypeNames() []string { return append([]string(nil), payloadTypes...) }

// DiscoverSources invokes discoverSources.
func (client *Client) DiscoverSources(ctx context.Context, payload DiscoverSourcesRequest, options ...InvocationOption) (TypedResponse[DiscoveryPlanResponse], error) {
	return callTyped[DiscoverSourcesRequest, DiscoveryPlanResponse](client, ctx, "discoverSources", payload, options...)
}

// IngestCatalog invokes ingestCatalog.
func (client *Client) IngestCatalog(ctx context.Context, payload IngestCatalogRequest, options ...InvocationOption) (TypedResponse[IngestionReceiptResponse], error) {
	return callTyped[IngestCatalogRequest, IngestionReceiptResponse](client, ctx, "ingestCatalog", payload, options...)
}

// GetSourceStatus invokes getSourceStatus.
func (client *Client) GetSourceStatus(ctx context.Context, payload SourceIdRequest, options ...InvocationOption) (TypedResponse[SourceStatusResponse], error) {
	return callTyped[SourceIdRequest, SourceStatusResponse](client, ctx, "getSourceStatus", payload, options...)
}

// QueryCatalog invokes queryCatalog.
func (client *Client) QueryCatalog(ctx context.Context, payload QueryCatalogRequest, options ...InvocationOption) (TypedResponse[CatalogQueryResponse], error) {
	return callTyped[QueryCatalogRequest, CatalogQueryResponse](client, ctx, "queryCatalog", payload, options...)
}

// BatchAtoms invokes batchAtoms.
func (client *Client) BatchAtoms(ctx context.Context, payload BatchAtomsRequest, options ...InvocationOption) (TypedResponse[AtomBatchResponse], error) {
	return callTyped[BatchAtomsRequest, AtomBatchResponse](client, ctx, "batchAtoms", payload, options...)
}

// TombstoneAtom invokes tombstoneAtom.
func (client *Client) TombstoneAtom(ctx context.Context, payload AtomIdRequest, options ...InvocationOption) (TypedResponse[MutationReceipt], error) {
	return callTyped[AtomIdRequest, MutationReceipt](client, ctx, "tombstoneAtom", payload, options...)
}

// CreateContextPlan invokes createContextPlan.
func (client *Client) CreateContextPlan(ctx context.Context, payload CreateContextPlanRequest, options ...InvocationOption) (TypedResponse[ContextPlanResponse], error) {
	return callTyped[CreateContextPlanRequest, ContextPlanResponse](client, ctx, "createContextPlan", payload, options...)
}

// CompileContextBundle invokes compileContextBundle.
func (client *Client) CompileContextBundle(ctx context.Context, payload CompileContextBundleRequest, options ...InvocationOption) (TypedResponse[ContextBundle], error) {
	return callTyped[CompileContextBundleRequest, ContextBundle](client, ctx, "compileContextBundle", payload, options...)
}

// CompileContextDelta invokes compileContextDelta.
func (client *Client) CompileContextDelta(ctx context.Context, payload CompileContextDeltaRequest, options ...InvocationOption) (TypedResponse[ContextDeltaResponse], error) {
	return callTyped[CompileContextDeltaRequest, ContextDeltaResponse](client, ctx, "compileContextDelta", payload, options...)
}

// GetContextBundle invokes getContextBundle.
func (client *Client) GetContextBundle(ctx context.Context, payload BundleIdRequest, options ...InvocationOption) (TypedResponse[ContextBundle], error) {
	return callTyped[BundleIdRequest, ContextBundle](client, ctx, "getContextBundle", payload, options...)
}

// GetContextBundleManifest invokes getContextBundleManifest.
func (client *Client) GetContextBundleManifest(ctx context.Context, payload BundleIdRequest, options ...InvocationOption) (TypedResponse[SelectionManifest], error) {
	return callTyped[BundleIdRequest, SelectionManifest](client, ctx, "getContextBundleManifest", payload, options...)
}

// ExplainContextBundle invokes explainContextBundle.
func (client *Client) ExplainContextBundle(ctx context.Context, payload ExplainContextBundleRequest, options ...InvocationOption) (TypedResponse[ContextExplanationResponse], error) {
	return callTyped[ExplainContextBundleRequest, ContextExplanationResponse](client, ctx, "explainContextBundle", payload, options...)
}

// MaterializeContextBundle invokes materializeContextBundle.
func (client *Client) MaterializeContextBundle(ctx context.Context, payload MaterializeContextBundleRequest, options ...InvocationOption) (TypedResponse[MaterializationResponse], error) {
	return callTyped[MaterializeContextBundleRequest, MaterializationResponse](client, ctx, "materializeContextBundle", payload, options...)
}

// RevalidateContextBundle invokes revalidateContextBundle.
func (client *Client) RevalidateContextBundle(ctx context.Context, payload BundleIdRequest, options ...InvocationOption) (TypedResponse[RevalidationResponse], error) {
	return callTyped[BundleIdRequest, RevalidationResponse](client, ctx, "revalidateContextBundle", payload, options...)
}

// CreateSpace invokes createSpace.
func (client *Client) CreateSpace(ctx context.Context, payload CreateSpaceRequest, options ...InvocationOption) (TypedResponse[ContextCommit], error) {
	return callTyped[CreateSpaceRequest, ContextCommit](client, ctx, "createSpace", payload, options...)
}

// ForkSpace invokes forkSpace.
func (client *Client) ForkSpace(ctx context.Context, payload ForkSpaceRequest, options ...InvocationOption) (TypedResponse[SpaceForkResponse], error) {
	return callTyped[ForkSpaceRequest, SpaceForkResponse](client, ctx, "forkSpace", payload, options...)
}

// PublishSpace invokes publishSpace.
func (client *Client) PublishSpace(ctx context.Context, payload PublishSpaceRequest, options ...InvocationOption) (TypedResponse[SpacePublishResponse], error) {
	return callTyped[PublishSpaceRequest, SpacePublishResponse](client, ctx, "publishSpace", payload, options...)
}

// GetSpaceLog invokes getSpaceLog.
func (client *Client) GetSpaceLog(ctx context.Context, payload SpaceIdRequest, options ...InvocationOption) (TypedResponse[SpaceLogResponse], error) {
	return callTyped[SpaceIdRequest, SpaceLogResponse](client, ctx, "getSpaceLog", payload, options...)
}

// SubscribeSpaceEvents opens the resumable subscribeSpaceEvents event stream.
func (client *Client) SubscribeSpaceEvents(ctx context.Context, payload SpaceIdRequest, options ...InvocationOption) (*TypedEventStream[SpaceEventPayload], error) {
	return streamTyped[SpaceIdRequest, SpaceEventPayload](client, ctx, "subscribeSpaceEvents", payload, options...)
}

// CreateSpaceCheckpoint invokes createSpaceCheckpoint.
func (client *Client) CreateSpaceCheckpoint(ctx context.Context, payload CheckpointSpaceRequest, options ...InvocationOption) (TypedResponse[SpaceCheckpointResponse], error) {
	return callTyped[CheckpointSpaceRequest, SpaceCheckpointResponse](client, ctx, "createSpaceCheckpoint", payload, options...)
}

// ListSpaceConflicts invokes listSpaceConflicts.
func (client *Client) ListSpaceConflicts(ctx context.Context, payload SpaceIdRequest, options ...InvocationOption) (TypedResponse[ConflictListResponse], error) {
	return callTyped[SpaceIdRequest, ConflictListResponse](client, ctx, "listSpaceConflicts", payload, options...)
}

// ResolveSpaceConflict invokes resolveSpaceConflict.
func (client *Client) ResolveSpaceConflict(ctx context.Context, payload ResolveSpaceConflictRequest, options ...InvocationOption) (TypedResponse[ConflictResolutionResponse], error) {
	return callTyped[ResolveSpaceConflictRequest, ConflictResolutionResponse](client, ctx, "resolveSpaceConflict", payload, options...)
}

// CreateHandoff invokes createHandoff.
func (client *Client) CreateHandoff(ctx context.Context, payload CreateHandoffRequest, options ...InvocationOption) (TypedResponse[CreateHandoffResponse], error) {
	return callTyped[CreateHandoffRequest, CreateHandoffResponse](client, ctx, "createHandoff", payload, options...)
}

// PreviewHandoff invokes previewHandoff.
func (client *Client) PreviewHandoff(ctx context.Context, payload HandoffIdRequest, options ...InvocationOption) (TypedResponse[HandoffPreviewResponse], error) {
	return callTyped[HandoffIdRequest, HandoffPreviewResponse](client, ctx, "previewHandoff", payload, options...)
}

// AcceptHandoff invokes acceptHandoff.
func (client *Client) AcceptHandoff(ctx context.Context, payload AcceptHandoffRequest, options ...InvocationOption) (TypedResponse[HandoffAcceptance], error) {
	return callTyped[AcceptHandoffRequest, HandoffAcceptance](client, ctx, "acceptHandoff", payload, options...)
}

// RevokeHandoff invokes revokeHandoff.
func (client *Client) RevokeHandoff(ctx context.Context, payload RevokeHandoffRequest, options ...InvocationOption) (TypedResponse[MutationReceipt], error) {
	return callTyped[RevokeHandoffRequest, MutationReceipt](client, ctx, "revokeHandoff", payload, options...)
}

// RecordHandoffResult invokes recordHandoffResult.
func (client *Client) RecordHandoffResult(ctx context.Context, payload RecordHandoffResultRequest, options ...InvocationOption) (TypedResponse[HandoffResultReceipt], error) {
	return callTyped[RecordHandoffResultRequest, HandoffResultReceipt](client, ctx, "recordHandoffResult", payload, options...)
}

// MergeHandoff invokes mergeHandoff.
func (client *Client) MergeHandoff(ctx context.Context, payload MergeHandoffRequest, options ...InvocationOption) (TypedResponse[HandoffMergeResponse], error) {
	return callTyped[MergeHandoffRequest, HandoffMergeResponse](client, ctx, "mergeHandoff", payload, options...)
}

// PrepareEffect invokes prepareEffect.
func (client *Client) PrepareEffect(ctx context.Context, payload PrepareEffectRequest, options ...InvocationOption) (TypedResponse[EffectStatusResponse], error) {
	return callTyped[PrepareEffectRequest, EffectStatusResponse](client, ctx, "prepareEffect", payload, options...)
}

// AuthorizeEffect invokes authorizeEffect.
func (client *Client) AuthorizeEffect(ctx context.Context, payload AuthorizeEffectRequest, options ...InvocationOption) (TypedResponse[EffectStatusResponse], error) {
	return callTyped[AuthorizeEffectRequest, EffectStatusResponse](client, ctx, "authorizeEffect", payload, options...)
}

// DispatchEffect invokes dispatchEffect.
func (client *Client) DispatchEffect(ctx context.Context, payload EffectIdRequest, options ...InvocationOption) (TypedResponse[EffectStatusResponse], error) {
	return callTyped[EffectIdRequest, EffectStatusResponse](client, ctx, "dispatchEffect", payload, options...)
}

// GetEffectStatus invokes getEffectStatus.
func (client *Client) GetEffectStatus(ctx context.Context, payload EffectIdRequest, options ...InvocationOption) (TypedResponse[EffectStatusResponse], error) {
	return callTyped[EffectIdRequest, EffectStatusResponse](client, ctx, "getEffectStatus", payload, options...)
}

// ReconcileEffect invokes reconcileEffect.
func (client *Client) ReconcileEffect(ctx context.Context, payload EffectIdRequest, options ...InvocationOption) (TypedResponse[EffectStatusResponse], error) {
	return callTyped[EffectIdRequest, EffectStatusResponse](client, ctx, "reconcileEffect", payload, options...)
}

// CompensateEffect invokes compensateEffect.
func (client *Client) CompensateEffect(ctx context.Context, payload CompensateEffectRequest, options ...InvocationOption) (TypedResponse[EffectStatusResponse], error) {
	return callTyped[CompensateEffectRequest, EffectStatusResponse](client, ctx, "compensateEffect", payload, options...)
}

// CreateReplay invokes createReplay.
func (client *Client) CreateReplay(ctx context.Context, payload CreateReplayRequest, options ...InvocationOption) (TypedResponse[ReplayJobResponse], error) {
	return callTyped[CreateReplayRequest, ReplayJobResponse](client, ctx, "createReplay", payload, options...)
}

// RunObservationalReplay invokes runObservationalReplay.
func (client *Client) RunObservationalReplay(ctx context.Context, payload ReplayIdRequest, options ...InvocationOption) (TypedResponse[ReplayExecution], error) {
	return callTyped[ReplayIdRequest, ReplayExecution](client, ctx, "runObservationalReplay", payload, options...)
}

// CompareLiveReplay invokes compareLiveReplay.
func (client *Client) CompareLiveReplay(ctx context.Context, payload CompareLiveReplayRequest, options ...InvocationOption) (TypedResponse[ReplayExecution], error) {
	return callTyped[CompareLiveReplayRequest, ReplayExecution](client, ctx, "compareLiveReplay", payload, options...)
}

// GetReplayCompleteness invokes getReplayCompleteness.
func (client *Client) GetReplayCompleteness(ctx context.Context, payload ReplayIdRequest, options ...InvocationOption) (TypedResponse[ReplayCompleteness], error) {
	return callTyped[ReplayIdRequest, ReplayCompleteness](client, ctx, "getReplayCompleteness", payload, options...)
}

// GetLiveness invokes getLiveness.
func (client *Client) GetLiveness(ctx context.Context, payload EmptyRequest, options ...InvocationOption) (TypedResponse[LivenessResponse], error) {
	return callTyped[EmptyRequest, LivenessResponse](client, ctx, "getLiveness", payload, options...)
}

// GetReadiness invokes getReadiness.
func (client *Client) GetReadiness(ctx context.Context, payload EmptyRequest, options ...InvocationOption) (TypedResponse[ReadinessResponse], error) {
	return callTyped[EmptyRequest, ReadinessResponse](client, ctx, "getReadiness", payload, options...)
}

// GetVersion invokes getVersion.
func (client *Client) GetVersion(ctx context.Context, payload EmptyRequest, options ...InvocationOption) (TypedResponse[VersionResponse], error) {
	return callTyped[EmptyRequest, VersionResponse](client, ctx, "getVersion", payload, options...)
}

// GetCapabilities invokes getCapabilities.
func (client *Client) GetCapabilities(ctx context.Context, payload EmptyRequest, options ...InvocationOption) (TypedResponse[CapabilitiesResponse], error) {
	return callTyped[EmptyRequest, CapabilitiesResponse](client, ctx, "getCapabilities", payload, options...)
}

// GetConfiguration invokes getConfiguration.
func (client *Client) GetConfiguration(ctx context.Context, payload EmptyRequest, options ...InvocationOption) (TypedResponse[ConfigurationResponse], error) {
	return callTyped[EmptyRequest, ConfigurationResponse](client, ctx, "getConfiguration", payload, options...)
}

// GetDiagnostics invokes getDiagnostics.
func (client *Client) GetDiagnostics(ctx context.Context, payload EmptyRequest, options ...InvocationOption) (TypedResponse[DiagnosticsResponse], error) {
	return callTyped[EmptyRequest, DiagnosticsResponse](client, ctx, "getDiagnostics", payload, options...)
}

// GetMetrics invokes getMetrics.
func (client *Client) GetMetrics(ctx context.Context, payload EmptyRequest, options ...InvocationOption) (TypedResponse[MetricsResponse], error) {
	return callTyped[EmptyRequest, MetricsResponse](client, ctx, "getMetrics", payload, options...)
}

// DiscoverSources invokes discoverSources over gRPC.
func (client *GRPCClient) DiscoverSources(ctx context.Context, payload DiscoverSourcesRequest, options ...InvocationOption) (TypedResponse[DiscoveryPlanResponse], error) {
	return callGRPCTyped[DiscoverSourcesRequest, DiscoveryPlanResponse](client, ctx, "discoverSources", payload, options...)
}

// IngestCatalog invokes ingestCatalog over gRPC.
func (client *GRPCClient) IngestCatalog(ctx context.Context, payload IngestCatalogRequest, options ...InvocationOption) (TypedResponse[IngestionReceiptResponse], error) {
	return callGRPCTyped[IngestCatalogRequest, IngestionReceiptResponse](client, ctx, "ingestCatalog", payload, options...)
}

// GetSourceStatus invokes getSourceStatus over gRPC.
func (client *GRPCClient) GetSourceStatus(ctx context.Context, payload SourceIdRequest, options ...InvocationOption) (TypedResponse[SourceStatusResponse], error) {
	return callGRPCTyped[SourceIdRequest, SourceStatusResponse](client, ctx, "getSourceStatus", payload, options...)
}

// QueryCatalog invokes queryCatalog over gRPC.
func (client *GRPCClient) QueryCatalog(ctx context.Context, payload QueryCatalogRequest, options ...InvocationOption) (TypedResponse[CatalogQueryResponse], error) {
	return callGRPCTyped[QueryCatalogRequest, CatalogQueryResponse](client, ctx, "queryCatalog", payload, options...)
}

// BatchAtoms invokes batchAtoms over gRPC.
func (client *GRPCClient) BatchAtoms(ctx context.Context, payload BatchAtomsRequest, options ...InvocationOption) (TypedResponse[AtomBatchResponse], error) {
	return callGRPCTyped[BatchAtomsRequest, AtomBatchResponse](client, ctx, "batchAtoms", payload, options...)
}

// TombstoneAtom invokes tombstoneAtom over gRPC.
func (client *GRPCClient) TombstoneAtom(ctx context.Context, payload AtomIdRequest, options ...InvocationOption) (TypedResponse[MutationReceipt], error) {
	return callGRPCTyped[AtomIdRequest, MutationReceipt](client, ctx, "tombstoneAtom", payload, options...)
}

// CreateContextPlan invokes createContextPlan over gRPC.
func (client *GRPCClient) CreateContextPlan(ctx context.Context, payload CreateContextPlanRequest, options ...InvocationOption) (TypedResponse[ContextPlanResponse], error) {
	return callGRPCTyped[CreateContextPlanRequest, ContextPlanResponse](client, ctx, "createContextPlan", payload, options...)
}

// CompileContextBundle invokes compileContextBundle over gRPC.
func (client *GRPCClient) CompileContextBundle(ctx context.Context, payload CompileContextBundleRequest, options ...InvocationOption) (TypedResponse[ContextBundle], error) {
	return callGRPCTyped[CompileContextBundleRequest, ContextBundle](client, ctx, "compileContextBundle", payload, options...)
}

// CompileContextDelta invokes compileContextDelta over gRPC.
func (client *GRPCClient) CompileContextDelta(ctx context.Context, payload CompileContextDeltaRequest, options ...InvocationOption) (TypedResponse[ContextDeltaResponse], error) {
	return callGRPCTyped[CompileContextDeltaRequest, ContextDeltaResponse](client, ctx, "compileContextDelta", payload, options...)
}

// GetContextBundle invokes getContextBundle over gRPC.
func (client *GRPCClient) GetContextBundle(ctx context.Context, payload BundleIdRequest, options ...InvocationOption) (TypedResponse[ContextBundle], error) {
	return callGRPCTyped[BundleIdRequest, ContextBundle](client, ctx, "getContextBundle", payload, options...)
}

// GetContextBundleManifest invokes getContextBundleManifest over gRPC.
func (client *GRPCClient) GetContextBundleManifest(ctx context.Context, payload BundleIdRequest, options ...InvocationOption) (TypedResponse[SelectionManifest], error) {
	return callGRPCTyped[BundleIdRequest, SelectionManifest](client, ctx, "getContextBundleManifest", payload, options...)
}

// ExplainContextBundle invokes explainContextBundle over gRPC.
func (client *GRPCClient) ExplainContextBundle(ctx context.Context, payload ExplainContextBundleRequest, options ...InvocationOption) (TypedResponse[ContextExplanationResponse], error) {
	return callGRPCTyped[ExplainContextBundleRequest, ContextExplanationResponse](client, ctx, "explainContextBundle", payload, options...)
}

// MaterializeContextBundle invokes materializeContextBundle over gRPC.
func (client *GRPCClient) MaterializeContextBundle(ctx context.Context, payload MaterializeContextBundleRequest, options ...InvocationOption) (TypedResponse[MaterializationResponse], error) {
	return callGRPCTyped[MaterializeContextBundleRequest, MaterializationResponse](client, ctx, "materializeContextBundle", payload, options...)
}

// RevalidateContextBundle invokes revalidateContextBundle over gRPC.
func (client *GRPCClient) RevalidateContextBundle(ctx context.Context, payload BundleIdRequest, options ...InvocationOption) (TypedResponse[RevalidationResponse], error) {
	return callGRPCTyped[BundleIdRequest, RevalidationResponse](client, ctx, "revalidateContextBundle", payload, options...)
}

// CreateSpace invokes createSpace over gRPC.
func (client *GRPCClient) CreateSpace(ctx context.Context, payload CreateSpaceRequest, options ...InvocationOption) (TypedResponse[ContextCommit], error) {
	return callGRPCTyped[CreateSpaceRequest, ContextCommit](client, ctx, "createSpace", payload, options...)
}

// ForkSpace invokes forkSpace over gRPC.
func (client *GRPCClient) ForkSpace(ctx context.Context, payload ForkSpaceRequest, options ...InvocationOption) (TypedResponse[SpaceForkResponse], error) {
	return callGRPCTyped[ForkSpaceRequest, SpaceForkResponse](client, ctx, "forkSpace", payload, options...)
}

// PublishSpace invokes publishSpace over gRPC.
func (client *GRPCClient) PublishSpace(ctx context.Context, payload PublishSpaceRequest, options ...InvocationOption) (TypedResponse[SpacePublishResponse], error) {
	return callGRPCTyped[PublishSpaceRequest, SpacePublishResponse](client, ctx, "publishSpace", payload, options...)
}

// GetSpaceLog invokes getSpaceLog over gRPC.
func (client *GRPCClient) GetSpaceLog(ctx context.Context, payload SpaceIdRequest, options ...InvocationOption) (TypedResponse[SpaceLogResponse], error) {
	return callGRPCTyped[SpaceIdRequest, SpaceLogResponse](client, ctx, "getSpaceLog", payload, options...)
}

// SubscribeSpaceEvents opens the resumable subscribeSpaceEvents gRPC event stream.
func (client *GRPCClient) SubscribeSpaceEvents(ctx context.Context, payload SpaceIdRequest, options ...InvocationOption) (*TypedEventStream[SpaceEventPayload], error) {
	return streamGRPCTyped[SpaceIdRequest, SpaceEventPayload](client, ctx, "subscribeSpaceEvents", payload, options...)
}

// CreateSpaceCheckpoint invokes createSpaceCheckpoint over gRPC.
func (client *GRPCClient) CreateSpaceCheckpoint(ctx context.Context, payload CheckpointSpaceRequest, options ...InvocationOption) (TypedResponse[SpaceCheckpointResponse], error) {
	return callGRPCTyped[CheckpointSpaceRequest, SpaceCheckpointResponse](client, ctx, "createSpaceCheckpoint", payload, options...)
}

// ListSpaceConflicts invokes listSpaceConflicts over gRPC.
func (client *GRPCClient) ListSpaceConflicts(ctx context.Context, payload SpaceIdRequest, options ...InvocationOption) (TypedResponse[ConflictListResponse], error) {
	return callGRPCTyped[SpaceIdRequest, ConflictListResponse](client, ctx, "listSpaceConflicts", payload, options...)
}

// ResolveSpaceConflict invokes resolveSpaceConflict over gRPC.
func (client *GRPCClient) ResolveSpaceConflict(ctx context.Context, payload ResolveSpaceConflictRequest, options ...InvocationOption) (TypedResponse[ConflictResolutionResponse], error) {
	return callGRPCTyped[ResolveSpaceConflictRequest, ConflictResolutionResponse](client, ctx, "resolveSpaceConflict", payload, options...)
}

// CreateHandoff invokes createHandoff over gRPC.
func (client *GRPCClient) CreateHandoff(ctx context.Context, payload CreateHandoffRequest, options ...InvocationOption) (TypedResponse[CreateHandoffResponse], error) {
	return callGRPCTyped[CreateHandoffRequest, CreateHandoffResponse](client, ctx, "createHandoff", payload, options...)
}

// PreviewHandoff invokes previewHandoff over gRPC.
func (client *GRPCClient) PreviewHandoff(ctx context.Context, payload HandoffIdRequest, options ...InvocationOption) (TypedResponse[HandoffPreviewResponse], error) {
	return callGRPCTyped[HandoffIdRequest, HandoffPreviewResponse](client, ctx, "previewHandoff", payload, options...)
}

// AcceptHandoff invokes acceptHandoff over gRPC.
func (client *GRPCClient) AcceptHandoff(ctx context.Context, payload AcceptHandoffRequest, options ...InvocationOption) (TypedResponse[HandoffAcceptance], error) {
	return callGRPCTyped[AcceptHandoffRequest, HandoffAcceptance](client, ctx, "acceptHandoff", payload, options...)
}

// RevokeHandoff invokes revokeHandoff over gRPC.
func (client *GRPCClient) RevokeHandoff(ctx context.Context, payload RevokeHandoffRequest, options ...InvocationOption) (TypedResponse[MutationReceipt], error) {
	return callGRPCTyped[RevokeHandoffRequest, MutationReceipt](client, ctx, "revokeHandoff", payload, options...)
}

// RecordHandoffResult invokes recordHandoffResult over gRPC.
func (client *GRPCClient) RecordHandoffResult(ctx context.Context, payload RecordHandoffResultRequest, options ...InvocationOption) (TypedResponse[HandoffResultReceipt], error) {
	return callGRPCTyped[RecordHandoffResultRequest, HandoffResultReceipt](client, ctx, "recordHandoffResult", payload, options...)
}

// MergeHandoff invokes mergeHandoff over gRPC.
func (client *GRPCClient) MergeHandoff(ctx context.Context, payload MergeHandoffRequest, options ...InvocationOption) (TypedResponse[HandoffMergeResponse], error) {
	return callGRPCTyped[MergeHandoffRequest, HandoffMergeResponse](client, ctx, "mergeHandoff", payload, options...)
}

// PrepareEffect invokes prepareEffect over gRPC.
func (client *GRPCClient) PrepareEffect(ctx context.Context, payload PrepareEffectRequest, options ...InvocationOption) (TypedResponse[EffectStatusResponse], error) {
	return callGRPCTyped[PrepareEffectRequest, EffectStatusResponse](client, ctx, "prepareEffect", payload, options...)
}

// AuthorizeEffect invokes authorizeEffect over gRPC.
func (client *GRPCClient) AuthorizeEffect(ctx context.Context, payload AuthorizeEffectRequest, options ...InvocationOption) (TypedResponse[EffectStatusResponse], error) {
	return callGRPCTyped[AuthorizeEffectRequest, EffectStatusResponse](client, ctx, "authorizeEffect", payload, options...)
}

// DispatchEffect invokes dispatchEffect over gRPC.
func (client *GRPCClient) DispatchEffect(ctx context.Context, payload EffectIdRequest, options ...InvocationOption) (TypedResponse[EffectStatusResponse], error) {
	return callGRPCTyped[EffectIdRequest, EffectStatusResponse](client, ctx, "dispatchEffect", payload, options...)
}

// GetEffectStatus invokes getEffectStatus over gRPC.
func (client *GRPCClient) GetEffectStatus(ctx context.Context, payload EffectIdRequest, options ...InvocationOption) (TypedResponse[EffectStatusResponse], error) {
	return callGRPCTyped[EffectIdRequest, EffectStatusResponse](client, ctx, "getEffectStatus", payload, options...)
}

// ReconcileEffect invokes reconcileEffect over gRPC.
func (client *GRPCClient) ReconcileEffect(ctx context.Context, payload EffectIdRequest, options ...InvocationOption) (TypedResponse[EffectStatusResponse], error) {
	return callGRPCTyped[EffectIdRequest, EffectStatusResponse](client, ctx, "reconcileEffect", payload, options...)
}

// CompensateEffect invokes compensateEffect over gRPC.
func (client *GRPCClient) CompensateEffect(ctx context.Context, payload CompensateEffectRequest, options ...InvocationOption) (TypedResponse[EffectStatusResponse], error) {
	return callGRPCTyped[CompensateEffectRequest, EffectStatusResponse](client, ctx, "compensateEffect", payload, options...)
}

// CreateReplay invokes createReplay over gRPC.
func (client *GRPCClient) CreateReplay(ctx context.Context, payload CreateReplayRequest, options ...InvocationOption) (TypedResponse[ReplayJobResponse], error) {
	return callGRPCTyped[CreateReplayRequest, ReplayJobResponse](client, ctx, "createReplay", payload, options...)
}

// RunObservationalReplay invokes runObservationalReplay over gRPC.
func (client *GRPCClient) RunObservationalReplay(ctx context.Context, payload ReplayIdRequest, options ...InvocationOption) (TypedResponse[ReplayExecution], error) {
	return callGRPCTyped[ReplayIdRequest, ReplayExecution](client, ctx, "runObservationalReplay", payload, options...)
}

// CompareLiveReplay invokes compareLiveReplay over gRPC.
func (client *GRPCClient) CompareLiveReplay(ctx context.Context, payload CompareLiveReplayRequest, options ...InvocationOption) (TypedResponse[ReplayExecution], error) {
	return callGRPCTyped[CompareLiveReplayRequest, ReplayExecution](client, ctx, "compareLiveReplay", payload, options...)
}

// GetReplayCompleteness invokes getReplayCompleteness over gRPC.
func (client *GRPCClient) GetReplayCompleteness(ctx context.Context, payload ReplayIdRequest, options ...InvocationOption) (TypedResponse[ReplayCompleteness], error) {
	return callGRPCTyped[ReplayIdRequest, ReplayCompleteness](client, ctx, "getReplayCompleteness", payload, options...)
}

// GetLiveness invokes getLiveness over gRPC.
func (client *GRPCClient) GetLiveness(ctx context.Context, payload EmptyRequest, options ...InvocationOption) (TypedResponse[LivenessResponse], error) {
	return callGRPCTyped[EmptyRequest, LivenessResponse](client, ctx, "getLiveness", payload, options...)
}

// GetReadiness invokes getReadiness over gRPC.
func (client *GRPCClient) GetReadiness(ctx context.Context, payload EmptyRequest, options ...InvocationOption) (TypedResponse[ReadinessResponse], error) {
	return callGRPCTyped[EmptyRequest, ReadinessResponse](client, ctx, "getReadiness", payload, options...)
}

// GetVersion invokes getVersion over gRPC.
func (client *GRPCClient) GetVersion(ctx context.Context, payload EmptyRequest, options ...InvocationOption) (TypedResponse[VersionResponse], error) {
	return callGRPCTyped[EmptyRequest, VersionResponse](client, ctx, "getVersion", payload, options...)
}

// GetCapabilities invokes getCapabilities over gRPC.
func (client *GRPCClient) GetCapabilities(ctx context.Context, payload EmptyRequest, options ...InvocationOption) (TypedResponse[CapabilitiesResponse], error) {
	return callGRPCTyped[EmptyRequest, CapabilitiesResponse](client, ctx, "getCapabilities", payload, options...)
}

// GetConfiguration invokes getConfiguration over gRPC.
func (client *GRPCClient) GetConfiguration(ctx context.Context, payload EmptyRequest, options ...InvocationOption) (TypedResponse[ConfigurationResponse], error) {
	return callGRPCTyped[EmptyRequest, ConfigurationResponse](client, ctx, "getConfiguration", payload, options...)
}

// GetDiagnostics invokes getDiagnostics over gRPC.
func (client *GRPCClient) GetDiagnostics(ctx context.Context, payload EmptyRequest, options ...InvocationOption) (TypedResponse[DiagnosticsResponse], error) {
	return callGRPCTyped[EmptyRequest, DiagnosticsResponse](client, ctx, "getDiagnostics", payload, options...)
}

// GetMetrics invokes getMetrics over gRPC.
func (client *GRPCClient) GetMetrics(ctx context.Context, payload EmptyRequest, options ...InvocationOption) (TypedResponse[MetricsResponse], error) {
	return callGRPCTyped[EmptyRequest, MetricsResponse](client, ctx, "getMetrics", payload, options...)
}
