//! Concurrent monotonic UUIDv7 generation with clock-rollback handling.

use super::{CryptoError, CryptoErrorCode};
use std::fmt;
use std::sync::Mutex;
use std::time::{SystemTime, UNIX_EPOCH};

const UUID_BYTES: usize = 16;
const RANDOM_SEQUENCE_BYTES: usize = 10;
const MAX_UNIX_MILLISECONDS: u64 = (1_u64 << 48) - 1;

/// Valid RFC 9562 UUIDv7 bytes generated by the monotonic provider.
#[derive(Clone, Copy, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct UuidV7([u8; UUID_BYTES]);

impl UuidV7 {
    /// Returns the exact 16 UUID bytes.
    #[must_use]
    pub const fn as_bytes(&self) -> &[u8; UUID_BYTES] {
        &self.0
    }
}

impl fmt::Display for UuidV7 {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        for (index, byte) in self.0.iter().enumerate() {
            if matches!(index, 4 | 6 | 8 | 10) {
                formatter.write_str("-")?;
            }
            write!(formatter, "{byte:02x}")?;
        }
        Ok(())
    }
}

impl fmt::Debug for UuidV7 {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_tuple("UuidV7")
            .field(&self.to_string())
            .finish()
    }
}

#[derive(Default)]
struct GeneratorState {
    initialized: bool,
    last_milliseconds: u64,
    sequence: [u8; RANDOM_SEQUENCE_BYTES],
}

/// Thread-safe UUIDv7 generator that never regresses on clock rollback.
#[derive(Default)]
pub struct MonotonicUuidV7Generator {
    state: Mutex<GeneratorState>,
}

impl fmt::Debug for MonotonicUuidV7Generator {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("MonotonicUuidV7Generator")
    }
}

impl MonotonicUuidV7Generator {
    /// Generates from the current system clock.
    pub fn generate(&self) -> Result<UuidV7, CryptoError> {
        let duration = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map_err(|_error| CryptoError::new(CryptoErrorCode::InvalidMetadata))?;
        let milliseconds = u64::try_from(duration.as_millis())
            .map_err(|_error| CryptoError::new(CryptoErrorCode::InvalidMetadata))?;
        self.generate_at(milliseconds)
    }

    /// Generates at a supplied Unix millisecond for deterministic clocks and rollback tests.
    pub fn generate_at(&self, milliseconds: u64) -> Result<UuidV7, CryptoError> {
        if milliseconds > MAX_UNIX_MILLISECONDS {
            return Err(CryptoError::new(CryptoErrorCode::InvalidMetadata));
        }
        let mut state = self
            .state
            .lock()
            .map_err(|_error| CryptoError::new(CryptoErrorCode::ProviderUnavailable))?;
        if !state.initialized || milliseconds > state.last_milliseconds {
            getrandom::fill(&mut state.sequence)
                .map_err(|_error| CryptoError::new(CryptoErrorCode::RandomUnavailable))?;
            let first = state
                .sequence
                .first_mut()
                .ok_or_else(|| CryptoError::new(CryptoErrorCode::IdExhausted))?;
            *first &= 0x03;
            state.last_milliseconds = milliseconds;
            state.initialized = true;
        } else {
            increment_sequence(&mut state.sequence)?;
        }
        Ok(pack_uuid(state.last_milliseconds, &state.sequence))
    }
}

fn increment_sequence(sequence: &mut [u8; RANDOM_SEQUENCE_BYTES]) -> Result<(), CryptoError> {
    for index in (0..RANDOM_SEQUENCE_BYTES).rev() {
        let maximum = if index == 0 { 0x03 } else { 0xff };
        let current = sequence
            .get(index)
            .copied()
            .ok_or_else(|| CryptoError::new(CryptoErrorCode::IdExhausted))?;
        if current < maximum {
            let slot = sequence
                .get_mut(index)
                .ok_or_else(|| CryptoError::new(CryptoErrorCode::IdExhausted))?;
            *slot += 1;
            for trailing in sequence.iter_mut().skip(index + 1) {
                *trailing = 0;
            }
            return Ok(());
        }
    }
    Err(CryptoError::new(CryptoErrorCode::IdExhausted))
}

fn pack_uuid(milliseconds: u64, sequence: &[u8; RANDOM_SEQUENCE_BYTES]) -> UuidV7 {
    let [_, _, t0, t1, t2, t3, t4, t5] = milliseconds.to_be_bytes();
    let &[s0, s1, s2, s3, s4, s5, s6, s7, s8, s9] = sequence;
    UuidV7([
        t0,
        t1,
        t2,
        t3,
        t4,
        t5,
        0x70 | ((s0 & 0x03) << 2) | (s1 >> 6),
        (s1 << 2) | (s2 >> 6),
        0x80 | (s2 & 0x3f),
        s3,
        s4,
        s5,
        s6,
        s7,
        s8,
        s9,
    ])
}

#[cfg(test)]
mod tests {
    use super::MonotonicUuidV7Generator;
    use std::collections::BTreeSet;
    use std::sync::Arc;

    #[test]
    fn rollback_retains_time_and_increments_monotonically() -> Result<(), Box<dyn std::error::Error>>
    {
        let generator = MonotonicUuidV7Generator::default();
        let first = generator.generate_at(1_700_000_000_001)?;
        let second = generator.generate_at(1_700_000_000_001)?;
        let rollback = generator.generate_at(1_699_999_999_000)?;
        assert!(first < second && second < rollback);
        for value in [first, second, rollback] {
            let text = value.to_string();
            assert_eq!(text.len(), 36);
            assert_eq!(text.as_bytes().get(14), Some(&b'7'));
            assert!(matches!(
                text.as_bytes().get(19),
                Some(b'8' | b'9' | b'a' | b'b')
            ));
        }
        Ok(())
    }

    #[test]
    fn concurrent_same_millisecond_generation_has_no_duplicates()
    -> Result<(), Box<dyn std::error::Error>> {
        let generator = Arc::new(MonotonicUuidV7Generator::default());
        let mut workers = Vec::new();
        for _worker in 0..8 {
            let generator = Arc::clone(&generator);
            workers.push(std::thread::spawn(move || {
                (0..1_000)
                    .map(|_index| generator.generate_at(1_700_000_000_000))
                    .collect::<Result<Vec<_>, _>>()
            }));
        }
        let mut values = BTreeSet::new();
        for worker in workers {
            let generated = worker.join().map_err(|_panic| "UUID worker panicked")??;
            values.extend(generated);
        }
        assert_eq!(values.len(), 8_000);
        Ok(())
    }
}
