"""Generated by sdk/generate_local_assets.py; edit sdk/native-platforms.v1.json."""

NATIVE_PLATFORMS: dict[str, dict[str, str]] = {
    "darwin-arm64": {
        "target": "aarch64-apple-darwin",
        "executable": "cigar-context-worker",
        "wheel_tag": "macosx_11_0_arm64"
    },
    "darwin-x64": {
        "target": "x86_64-apple-darwin",
        "executable": "cigar-context-worker",
        "wheel_tag": "macosx_11_0_x86_64"
    },
    "linux-x64-gnu": {
        "target": "x86_64-unknown-linux-gnu",
        "executable": "cigar-context-worker",
        "wheel_tag": "manylinux_2_28_x86_64"
    },
    "linux-arm64-gnu": {
        "target": "aarch64-unknown-linux-gnu",
        "executable": "cigar-context-worker",
        "wheel_tag": "manylinux_2_28_aarch64"
    },
    "linux-x64-musl": {
        "target": "x86_64-unknown-linux-musl",
        "executable": "cigar-context-worker",
        "wheel_tag": "musllinux_1_2_x86_64"
    },
    "linux-arm64-musl": {
        "target": "aarch64-unknown-linux-musl",
        "executable": "cigar-context-worker",
        "wheel_tag": "musllinux_1_2_aarch64"
    },
    "win32-x64": {
        "target": "x86_64-pc-windows-msvc",
        "executable": "cigar-context-worker.exe",
        "wheel_tag": "win_amd64"
    }
}
