#!/usr/bin/env python3
"""Generate packaged local-runtime metadata from the shared platform inventory."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def outputs() -> dict[Path, str]:
    inventory = json.loads((ROOT / "native-platforms.v1.json").read_text())
    if inventory["schema"] != "cigar.native-platforms.v1":
        raise ValueError("unexpected native platform schema")
    platforms = {
        row["id"]: {key: row[key] for key in ("target", "executable", "wheel_tag")}
        for row in inventory["platforms"]
    }
    if len(platforms) != len(inventory["platforms"]):
        raise ValueError("duplicate native platform")
    payload = json.dumps(platforms, indent=2)
    generated = {
        ROOT / "python/src/cigar_sdk/native-platforms.v1.json": (
            ROOT / "native-platforms.v1.json"
        ).read_text(),
        ROOT
        / "typescript/src/native-platforms.ts": "// Generated by sdk/generate_local_assets.py; edit sdk/native-platforms.v1.json.\n"
        f"export const NATIVE_PLATFORMS = {payload} as const;\n",
        ROOT
        / "python/src/cigar_sdk/native_platforms.py": '"""Generated by sdk/generate_local_assets.py; edit sdk/native-platforms.v1.json."""\n\n'
        f"NATIVE_PLATFORMS: dict[str, dict[str, str]] = {json.dumps(platforms, indent=4)}\n",
    }
    guide = (ROOT / "LOCAL_CONTEXT_GUIDE.md").read_text()
    discovery = (ROOT / "local-context-llms.txt").read_text()
    for directory in [
        ROOT / "typescript",
        ROOT / "python",
        ROOT / "python/src/cigar_sdk",
    ]:
        generated[directory / "AGENT_GUIDE.md"] = guide
        generated[directory / "llms.txt"] = discovery
    generated[ROOT.parent / "llms.txt"] = discovery
    generated[ROOT.parent / "docs/guides/local-context.md"] = guide
    return generated


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in outputs().items():
        if args.check:
            if not path.is_file() or path.read_text() != content:
                raise SystemExit(
                    f"generated local asset differs: {path.relative_to(ROOT.parent)}"
                )
        else:
            path.write_text(content)


if __name__ == "__main__":
    main()
